__author__ = 'jacob'

"""
data_frame_dict_to_csv.py

Takes a data frame dictionary generated by one of the filtering functions
and writes it to a csv file
"""

import csv


def write_to_csv(file_name, values):
    """
    writes the values to a csv file with the given file name
    """
    with open('csv_files/'+file_name+'.csv', 'w+') as f:
        csv_writer = csv.writer(f)
        for value in values:
            csv_writer.writerow(value)


def filtered_data_frame_to_csv(filtered_data_frame, filter_keys):
    """
    Creates multiple csv files where each csv file has the name of a value in the
    given filter keys and contains all the values with that filter value
    """
    for key in filter_keys:
        values = filtered_data_frame[filtered_data_frame['filter'] == key]
        write_to_csv(key, values.values)
